### ISSUE TITLE
mapping an array of files to detectiveEs6() gives an error

### ISSUE THREAD

**Issue by lmj0011** [dependents/node-detective-es6#9]
I'm passing an array of files to the function `detectiveEs6()`
ex.A gives me an error of the sort `Error: src was not given to detectiveEs6 `

```javascript
const detectiveEs6 = require('detective-es6');
//[...]
let files = [...]  //valid file paths
```

ex.A
```javascript
let importPrms = files.map((path)=> {

  let prm = new Promise((resolve, reject)=> {
    let src = fs.readFileSync(path, 'utf8');
    resolve(detectiveEs6(src));    // this throws an error
  });

  return prm;
});
```

ex.B
```javascript
let importPrms = files.map((path)=> {

  let prm = new Promise((resolve, reject)=> {
    let src = fs.readFileSync(path, 'utf8');
    resolve(detectiveEs6(src || ' '));  // this works
  });

  return prm;
});
```

**Comment by mrjoelkemp** [comment]
Thanks for filing an issue! 

Seems like one of the files is empty resulting in an empty string. This module should be modified to return an empty array when the src is an empty string. If src is undefined, it should throw an error. 

Would you like to make that change? Tests would be greatly appreciated. 

Thanks again for catching this.

**Comment by mrjoelkemp** [comment]
@lmj0011 I had some availability to work on this tonight; figured I'd get it fixed. I just cut a patch release with the fix.

Thanks again!

**Comment by lmj0011** [comment]
👍
